[manager]
prepend_keymap = [
    #{ on = "l",         run = "open",                        desc = "Open selected files" },
	#{ on = "L",         run = "open --interactive",          desc = "Open selected files interactively" },
	{ on = "<C-n>",    run = "tab_create --current", desc = "Create a new tab with CWD" },
    { on = "<Tab>",    run = "tab_switch 1 --relative", desc = "Switch to the next tab" },
	{ on = "<S-Tab>",  run = "tab_switch -1 --relative",  desc = "Switch to the previous tab" },
    { on = ["c","w"],  run = "rename --cursor=before_ext",  desc = "Rename selected file(s)" },
    { on = "<C-h>",    run = "hidden toggle",               desc = "Toggle the visibility of hidden files" },
]

